version: '3.8'
services:
  pos-mysql:
    image: mysql:8.0.30
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=demo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp